/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import {
  CatalogueProducts,
  CatalogueProductsId,
  Category,
  CategoryId,
  CategoryImage,
  Product,
  WebProducts,
  WebProductsCount,
  ProductId,
  ProductName,
  ProductImage,
  ProductImageId,
  ProductImageUrl,
} from "@/types";

export interface paths {
  "/api/v4/Catalogue/products": CatalogueProducts;
  "/api/v4/Catalogue/products/{id}": CatalogueProductsId;
  "/api/v4/Category": Category;
  "/api/v4/Category/{id}": CategoryId;
  "/api/v4/CategoryImage": CategoryImage;
  "/api/v4/Product": Product;
  "/api/v4/Product/WebProducts": WebProducts;
  "/api/v4/Product/WebProducts/Count": WebProductsCount;
  "/api/v4/Product/{id}": ProductId;
  "/api/v4/Product/name": ProductName;
  "/api/v4/ProductImage": ProductImage;
  "/api/v4/ProductImage/{id}": ProductImageId;
  "/api/v4/ProductImage/Url": ProductImageUrl;
}
